# .github/workflows/flutter-multi-platform.yml
name: Flutter Multi-Platform

on:
  #push:
  #  branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  #release:
  #  types: [published]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Create platforms Web
        run: flutter create .

      - name: Build Web
        run: flutter build web --release

      #- name: Upload web build
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: web-build
      #    path: build/web/

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Create platforms Android
        run: flutter create .

      - name: Build Android
        run: flutter build apk --release

      #- name: Upload APK
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: android-apk
      #    path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    runs-on: macos-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Create platforms ios
        run: flutter create .

      - name: Build ios
        run: flutter build ios --release --no-codesign

      #- name: Upload iOS build
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ios-build
      #    path: build/ios/